import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";
import multer from "multer";
import cors from "cors";
import dotenv from "dotenv";
import { Jimp } from "jimp";

dotenv.config();

const app = express();
const PORT = 3000;

app.use(cors());
app.use(express.json({ limit: '50mb' }));

const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
});

// API: Generate Character
app.post("/api/generate-character", async (req, res) => {
  const { prompt } = req.body;
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            text: `${prompt}, full body anime character, neutral frontal t-pose or a-pose, flat lighting, simple solid white background, high quality, character design sheet style, clean linework`,
          },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: '3:4',
        },
      },
    });

    let base64 = '';
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        base64 = part.inlineData.data;
        break;
      }
    }

    if (!base64) {
      throw new Error("No image was generated by the model. Try a different prompt.");
    }

    res.json({ imageUrl: `data:image/png;base64,${base64}` });
  } catch (error: any) {
    console.error("Generation Error:", error);
    // Specific check for paid tier requirement
    if (error.message?.includes('paid plans') || error.message?.includes('upgrade your account')) {
      return res.status(402).json({ 
        error: "Billing upgrade required", 
        message: "Image generation requires a paid Gemini API plan. Please click 'Configure API Key' to set up a billing-enabled key." 
      });
    }
    res.status(500).json({ error: error.message });
  }
});

// Helper: Process and Cut part from image
async function extractPart(originalJimp: any, part: any) {
  const width = originalJimp.width;
  const height = originalJimp.height;

  const [ymin, xmin, ymax, xmax] = part.bbox;
  
  const x = Math.max(0, Math.floor((xmin / 1000) * width));
  const y = Math.max(0, Math.floor((ymin / 1000) * height));
  const w = Math.min(width - x, Math.ceil(((xmax - xmin) / 1000) * width));
  const h = Math.min(height - y, Math.ceil(((ymax - ymin) / 1000) * height));

  if (w <= 0 || h <= 0) return null;

  // Clone and crop
  const cropped = originalJimp.clone().crop({ x, y, w, h });

  // Intelligent Background Removal (Simple White/Light Thresholding for Model Sheets)
  cropped.scan(0, 0, w, h, function(x: number, y: number, idx: number) {
    const r = this.bitmap.data[idx + 0];
    const g = this.bitmap.data[idx + 1];
    const b = this.bitmap.data[idx + 2];
    
    // If pixel is white-ish, make it transparent
    // Model sheets usually have flat white or very light grey backgrounds
    if (r > 240 && g > 240 && b > 240) {
      this.bitmap.data[idx + 3] = 0;
    }
  });

  const buffer = await cropped.getBuffer("image/png");
  return `data:image/png;base64,${buffer.toString('base64')}`;
}

// API: Analyze for Live2D Layers
app.post("/api/analyze-layers", async (req, res) => {
  const { image } = req.body; // base64
  
  if (!image) return res.status(400).json({ error: "Image required" });

  try {
    const base64Data = image.split(',')[1];
    const imagePart = {
      inlineData: {
        mimeType: "image/png",
        data: base64Data,
      },
    };

    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: {
        parts: [
          imagePart,
          {
            text: `Identify all Typical Live2D character parts in this image for professional rigging. 
            For each part, provide its name, its bounding box [ymin, xmin, ymax, xmax] in normalized coordinates (0-1000).
            Be extremely precise. Ensure symmetric parts (eyes, ears, arms, legs) are separated into Left and Right.
            
            Parts required: head, hair_front, hair_middle, hair_back, eye_L, eye_R, eyebrow_L, eyebrow_R, nose, mouth, ear_L, ear_R, neck, torso, arm_L, arm_R, hand_L, hand_R, leg_L, leg_R.
            
            Return ONLY a valid JSON object.`,
          },
        ],
      },
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            parts: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  name: { type: Type.STRING },
                  bbox: { 
                    type: Type.ARRAY, 
                    items: { type: Type.NUMBER },
                    description: "[ymin, xmin, ymax, xmax] in 0-1000 scale"
                  }
                },
                required: ["name", "bbox"]
              }
            }
          }
        }
      }
    });

    const result = JSON.parse(response.text);
    
    // Perform actual extraction
    const originalImage = await Jimp.read(Buffer.from(base64Data, 'base64'));
    
    const processedParts = await Promise.all(result.parts.map(async (part: any) => {
      const extractedUrl = await extractPart(originalImage, part);
      return { ...part, extractedUrl };
    }));

    res.json({ parts: processedParts.filter((p: any) => p.extractedUrl) });
  } catch (error: any) {
    console.error("Analysis Error:", error);
    res.status(500).json({ error: error.message });
  }
});

// Vite middleware for development
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
